---
before:
  hooks:
    - go mod download

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  skip: true

release:
  draft: true

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "shoekstra/{{ .ProjectName }}:latest"
      - "shoekstra/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/shoekstra/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/shoekstra/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - dockerfile: Dockerfile.alpine
    image_templates:
      - "shoekstra/{{ .ProjectName }}:latest-alpine"
      - "shoekstra/{{ .ProjectName }}:{{ .Tag }}-alpine"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/shoekstra/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/shoekstra/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
